# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "I'm Jacob"
tagline:          'Adventures in Data Science'
description:      'Data science graduate student by day, pretty much the same thing at night.'
url:              http://jacobsimmering.com
baseurl:          /

author:
  name:           'Jacob Simmering'
  url:            https://twitter.com/iacobus42

paginate:         5

# Custom vars
version:          3.0

github:
  repo:           https://github.com/iacobus42

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb